events {}

http {
	server {
		listen 80;
		
		# Serve sua página HTML
		location / {
			root /usr/share/nginx/html;
			index index.html;
		}

		# Endpoint de métricas - Só acessível dentro da rede Docker
		# O NGINX-EXPORTER lê daqui a cada scrape 
		location /nginx_status {
			stub_status;
			allow 127.0.0.1;
			allow 172.0.0.0/8;
			allow 10.1.1.220;
			deny all;
		}
	}
}
